name: METexpress CI/CD Workflow
on:
  push:
    branches:
      - develop
      - develop-ref
      - development
      - main_*
      - master
      - v4.0.*
      - feature_*
      - bugfix_*
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: ./.github/jobs/build_documentation.sh
      - uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: artifact/documentation
      - uses: actions/upload-artifact@v2
        with:
          name: documentation_warnings.log
          path: artifact/doc_warnings.log
          if-no-files-found: ignore
