name: Cleanup Untagged GHCR Images

on: 
  workflow_dispatch: # Manually
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

jobs:
  purge-untagged-images:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - met-airquality
          - met-anomalycor
          - met-cyclone
          - met-ensemble
          - met-object
          - met-precip
          - met-surface
          - met-upperair
    steps:
      - name: Delete image
        uses: snok/container-retention-policy@v2.1.3
        with:
          image-names: metexpress/development/${{ matrix.app }}
          cut-off: 1 day ago MST
          account-type: org
          org-name: dtcenter
          untagged-only: true
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
